POST https://auth-servisss.herokuapp.com/api/tokens
Content-Type: application/json

{
  "username": "RendL",
  "password": "pass"
}

> {% client.global.set("auth_token", response.body.token); %}

###

POST https://auth-servisss.herokuapp.com/api/users/new
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "MOMOO",
  "password": "MOMOO"
}

###

POST https://auth-servisss.herokuapp.com/api/tokens
Content-Type: application/json

{
  "username": "MOMOO",
  "password": "MOMOO"
}

> {% client.global.set("auth_token", response.body.token); %}

###

GET http://localhost:9999/api/products
Authorization: Bearer {{auth_token}}

###

POST http://localhost:9999/api/products/new
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Cola",
  "description": "black drink",
  "price": 600,
  "pic": "55d"
}

###

DELETE http://localhost:9999/api/products/4
Authorization: Bearer {{auth_token}}

###

